### PR TITLE
Update popup style.css to enhance readability with firefox or OS dark…

### PR DESCRIPTION
**Pull request by alkaphreak**
… theme.

### CODE REVIEW

**Comment by alkaphreak** [comment]
To quickly clode this issue : https://github.com/cgfrost/moolater/issues/11

**Comment by alkaphreak** [comment]
Is there anyone still here ?

**Comment by alkaphreak** [comment]
Nope ?

**Comment by cgfrost** [comment]
Hi @alkaphreak  I didn't get any notifications about this for some reason. I'm really sorry.

Merged now, will run a release soon.

**Pull request merged**
